---

- name: Add a new user
  user:
    name: "{{ user_name }}"
    comment: "{{ user_des }}"
    shell: /bin/bash
  tags:
    - add

- name: Give SSH access
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '../../../ssh-key/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - grant